### ISSUE TITLE
Execute Query returns error - curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.  and deployed engine shows Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method

### ISSUE THREAD

**Issue by washingon** [peoplehum/BagOfWords_SentimentAnalysis_Template#3]
Execute Query returns error.   ref https://github.com/peoplehum/BagOfWords_SentimentAnalysis_Template 
Run below request for processing query on serving layer, it will return sentiment and its probabilistic score.
curl -k -H "Content-Type: application/json" -d '{"phrase": "Freinds TV series is not good"}' https://localhost:8000/queries.json

curl -k -H "Content-Type: application/json" -d '{"phrase": "Freinds TV series is not good"}' https://192.168.5.140:8000/queries.json
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.

pio deploy
[WARN] [MasterActor] Nothing at http://192.168.5.140:8000
[INFO] [HttpListener] Bound to /192.168.5.140:8000
[INFO] [MasterActor] Engine is deployed and running. Engine API is live at http://192.168.5.140:8000.
[WARN] [HttpServerConnection] Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method

**Comment by bansarishah** [comment]
if you are using predictionIo version 0.10.0 or higher, it supports HTTP instead HTTPS.
 So query with:
curl -H "Content-Type: application/json" -d '{"phrase": "Freinds TV series is not good"}' http://192.168.5.140:8000/queries.json

**Comment by washingon** [comment]
my error.  i substituted http:  and query works.
thank you!
