### ISSUE TITLE
Typo in installation and setup

### ISSUE THREAD

**Issue by prasanthrj** [peoplehum/BagOfWords_SentimentAnalysis_Template#7]
please update below command in readme.md

python data/data/import_eventServer.py --access_key 3mZWDzci2D5YsqAnqNnXH9SB6Rg3dsTBs8iHkK6X2i54IQsIZI1eEeQQyMfs7b3F --file data/sample.csv

to 

 python data/import_eventServer.py --access_key 3mZWDzci2D5YsqAnqNnXH9SB6Rg3dsTBs8iHkK6X2i54IQsIZI1eEeQQyMfs7b3F --file data/sample.csv

**Comment by bansarishah** [comment]
Hi @prasanthrj, thank you for suggesting this typo. I will update it.
