### ISSUE TITLE
Wrong scoring with documentation sentences

### ISSUE THREAD

**Issue by JakubSzczesniak** [peoplehum/BagOfWords_SentimentAnalysis_Template#8]
I installed `BagOfWords_SentimentAnalysis_Template` and made `pio train` and send input json like

```
{"phrase": "It is good"}
```
and my output is
```
{
  "Sentiment": 0,
  "Score": 0.7461254419475105
}
```
all (positive) sent sentences outside of your training collection return `Sentiment: 0`

**Comment by bansarishah** [comment]
Hi @JakubSzczesniak, please train model with enough dataset. The dataset in sample.csv is not well balanced with positive and negative sentiment sentences, it can be used to test template is working properly or not. Please train model with dataset downloaded from (http://thinknook.com/twitter-sentiment-analysis-training-corpus-dataset-2012-09-22/).
If there are more queries or any suggestion for feature engineering part of the model, please put here.
Thank You.
